name          'puppet-oculus'
version       '0.1.0'
source        'https://github.com/tombooth/puppet-oculus.git'
author        'Tom Booth'
license       'MIT'
summary       'Puppet module to install oculus'
description   'Puppet module to install oculus'
project_page  'https://github.com/tombooth/puppet-oculus'

dependency 'puppetlabs/stdlib',    '>= 4.1.0'
dependency 'puppetlabs/vcsrepo',   '>= 0.2.0'
